function createfigure(A)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  stem matrix data

%  Auto-generated by MATLAB on 24-May-2019 21:19:09

% Create figure
figure1 = figure('Color',...
    [0.941176474094391 0.941176474094391 0.941176474094391]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to stem
stem1 = stem(A,'Marker','*','LineWidth',3,'LineStyle','none',...
    'Parent',axes1);
for i = 1:size(A, 2)-1
    set(stem1(i),'MarkerSize',5);
end

% Create xlabel
xlabel('Número de detecciones');

% Create ylabel
ylabel('\theta','FontSize',20);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[1 69]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-180 180]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',9,'YGrid','on','YTick',...
    [-180 -165 -150 -135 -120 -105 -90 -75 -60 -45 -30 -15 0 15 30 45 60 75 90 105 120 135 150 165 180]);
